### ISSUE TITLE
前置摄像头时，切换闪光灯 报错，可不可以设置不显示闪光灯啊

### ISSUE THREAD

**Issue by bakonMa** [Devil-Chen/DVMediaSelector#2]
java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:2174)
        at com.devil.library.camera.a.b(CameraInterface.java:274)
        at com.devil.library.camera.b.d.a(PreviewState.java:107)
        at com.devil.library.camera.b.c.a(CameraMachine.java:127)
        at com.devil.library.camera.JCameraView.g(JCameraView.java:600)
        at com.devil.library.camera.JCameraView.c(JCameraView.java:49)
        at com.devil.library.camera.JCameraView$1.onClick(JCameraView.java:179)
        at android.view.View.performClick(View.java:6659)
        at android.view.View.performClickInternal(View.java:6631)
        at android.view.View.access$3100(View.java:790)
        at android.view.View$PerformClick.run(View.java:26187)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

huawei nova 3e  切换闪光灯 闪退
oppo reno 没问题

**Comment by bakonMa** [comment]
看你commite 已经改了啊，赶快发版啊 哈哈
还有 设置了ALL 不显示视频的问题  
666

**Comment by bakonMa** [comment]
1.1.0  
进入拍照时，如果切换了摄像头，变成前置，返回再进入会是前置，没有恢复默认，闪光灯也会显示，还是会出现bug的情况

**Comment by longkehuawei** [comment]
java.lang.RuntimeException: takePicture failed
        at android.hardware.Camera.native_takePicture(Native Method)
        at android.hardware.Camera.takePicture(Camera.java:1623)
        at android.hardware.Camera.takePicture(Camera.java:1565)
        at com.devil.library.camera.a.a(CameraInterface.java:475)
        at com.devil.library.camera.b.d.a(PreviewState.java:66)
        at com.devil.library.camera.b.c.a(CameraMachine.java:96)
        at com.devil.library.camera.JCameraView$3.a(JCameraView.java:215)
        at com.devil.library.camera.CaptureLayout$2.a(CaptureLayout.java:151)
        at com.devil.library.camera.CaptureButton$2.onAnimationEnd(CaptureButton.java:237)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:552)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1232)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1474)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1097)
        at android.view.Choreographer.doCallbacks(Choreographer.java:900)
        at android.view.Choreographer.doFrame(Choreographer.java:813)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1085)
        at android.os.Handler.handleCallback(Handler.java:907)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7586)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
